// <auto-generated />
using System;
using EAMIS.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EAMIS.Core.Migrations
{
    [DbContext(typeof(EAMISContext))]
    partial class EAMISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISAUTHORIZATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AUTHORIZATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_AUTHORIZATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISBARANGAY", b =>
                {
                    b.Property<int>("BRGY_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BARANGAY_CODE")
                        .HasColumnType("int");

                    b.Property<string>("BRGY_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MUNICIPALITY_CODE")
                        .HasColumnType("int");

                    b.Property<int>("PROVINCE_CODE")
                        .HasColumnType("int");

                    b.Property<int>("REGION_CODE")
                        .HasColumnType("int");

                    b.HasKey("BRGY_CODE");

                    b.HasIndex("BARANGAY_CODE");

                    b.HasIndex("BRGY_CODE")
                        .IsUnique();

                    b.HasIndex("MUNICIPALITY_CODE");

                    b.HasIndex("PROVINCE_CODE");

                    b.HasIndex("REGION_CODE");

                    b.ToTable("EAMIS_BARANGAY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISCHARTOFACCOUNTS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACCOUNT_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CLASSIFICATIONID")
                        .HasColumnType("int");

                    b.Property<int?>("EAMISGENERALCHARTOFACCOUNTSID")
                        .HasColumnType("int");

                    b.Property<int>("GROUP_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_PART_OF_INVENTORY")
                        .HasColumnType("bit");

                    b.Property<string>("OBJECT_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SUBCLASSIFICATIONID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CLASSIFICATIONID");

                    b.HasIndex("EAMISGENERALCHARTOFACCOUNTSID");

                    b.HasIndex("GROUP_ID");

                    b.HasIndex("SUBCLASSIFICATIONID");

                    b.ToTable("EAMIS_CHART_OF_ACCOUNTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISCLASSIFICATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAME_CLASSIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_CLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISENVIRONMENTALIMPACTS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IMPACT_DESCPRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_ENVIRONMENTALIMPACTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISFINANCINGSOURCE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FINANCING_SOURCE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_FINANCING_SOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISFUNDSOURCE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AUTHORIZATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FINANCING_SOURCE_ID")
                        .HasColumnType("int");

                    b.Property<string>("FUND_CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GENERAL_FUND_SOURCE_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AUTHORIZATION_ID");

                    b.HasIndex("FINANCING_SOURCE_ID");

                    b.HasIndex("GENERAL_FUND_SOURCE_ID");

                    b.ToTable("EAMIS_FUND_SOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGENERALCHARTOFACCOUNTS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASSIFICATION_GROUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUB_CLASSIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_GENERAL_CHART_OF_ACCOUNTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGENERALFUNDSOURCE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_GENERAL_FUND_SOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGROUPCLASSIFICATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CHART_OF_ACCOUNT_ID")
                        .HasColumnType("int");

                    b.Property<int>("CLASSIFICATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("NAME_GROUPCLASSIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SUB_CLASSIFICATION_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CLASSIFICATION_ID");

                    b.HasIndex("SUB_CLASSIFICATION_ID");

                    b.ToTable("EAMIS_GROUP_CLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISITEMCATEGORY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CATEGORY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CHART_OF_ACCOUNT_ID")
                        .HasColumnType("int");

                    b.Property<string>("COST_METHOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPRECIATION_METHOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESTIMATED_LIFE")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_ASSET")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_SERIALIZED")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_STOCKABLE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_SUPPLIES")
                        .HasColumnType("bit");

                    b.Property<string>("SHORT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STOCK_QUANTITY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CHART_OF_ACCOUNT_ID");

                    b.ToTable("EAMIS_ITEM_CATEGORY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISITEMSUBCATEGORY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<int?>("PROPERTY_ITEMID")
                        .HasColumnType("int");

                    b.Property<string>("SUB_CATEGORY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORY_ID");

                    b.HasIndex("PROPERTY_ITEMID");

                    b.ToTable("EAMIS_ITEMS_SUB_CATEGORY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISMUNICIPALITY", b =>
                {
                    b.Property<int>("MUNICIPALITY_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CITY_MUNICIPALITY_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PROVINCE_CODE")
                        .HasColumnType("int");

                    b.Property<string>("PSGCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("REGION_CODE")
                        .HasColumnType("int");

                    b.HasKey("MUNICIPALITY_CODE");

                    b.HasIndex("MUNICIPALITY_CODE")
                        .IsUnique();

                    b.HasIndex("PROVINCE_CODE");

                    b.HasIndex("REGION_CODE");

                    b.ToTable("EAMIS_MUNICIPALITY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISNOTICEOFDELIVERY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DELIVERY_DATE")
                        .HasColumnType("int");

                    b.Property<string>("INSPECTION_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_INCOMPLETE_PROPERTY")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_WARRANTY_CERTIFICATE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_WATER_MATERAIL")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_WRONG_PROPERTY")
                        .HasColumnType("bit");

                    b.Property<int>("PROPERTY_DETAILS_ID")
                        .HasColumnType("int");

                    b.Property<int>("PUCHASE_ORDER_NO")
                        .HasColumnType("int");

                    b.Property<int>("PURCHASE_REQUEST_NO")
                        .HasColumnType("int");

                    b.Property<int>("TRANSACTION_ID")
                        .HasColumnType("int");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_NOTICE_OF_DELIVERY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPERSONNELINFO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BARANGAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DIRECTORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("EMPLOYEE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROVINCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("USERSUSER_ID")
                        .HasColumnType("int");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("USERSUSER_ID");

                    b.ToTable("EAMIS_APP_USER_INFO");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPRECONDITIONS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PARENT_ID")
                        .HasColumnType("int");

                    b.Property<string>("PRE_CONDITION_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PPECONDITIONS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROCUREMENTCATEGORY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("PROCUREMENT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PROCUREMENTCATEGORY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYDEPRECIATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DEPRECIATION_AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DEPRECIATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("PROPERTY_DETAILS_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PROPERTY_DEPRECIATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYDETAILS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BRAND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_PROPERTY")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_STOCKABLE")
                        .HasColumnType("bit");

                    b.Property<string>("MODEL_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PROPERTY_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<double>("QTY_IN_STOCK")
                        .HasColumnType("float");

                    b.Property<string>("SERIAL_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SOURCE_ID")
                        .HasColumnType("int");

                    b.Property<double>("STOCK_NO")
                        .HasColumnType("float");

                    b.Property<decimal>("UNIT_COST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UOM_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PROPERTY_DETAILS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYITEMS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APP_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRAND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("MODEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<int>("SUBCATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<int>("SUPPLIER_ID")
                        .HasColumnType("int");

                    b.Property<int>("UOM_ID")
                        .HasColumnType("int");

                    b.Property<int>("WAREHOUSE_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORY_ID");

                    b.HasIndex("SUPPLIER_ID");

                    b.HasIndex("UOM_ID");

                    b.HasIndex("WAREHOUSE_ID");

                    b.ToTable("EAMIS_PROPERTYITEMS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYTRANSFERDETAILS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FROM_USER_ID")
                        .HasColumnType("int");

                    b.Property<string>("PROPERTY_TRANSFER_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TO_USER_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TRANSFER_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PROPERTY_TRANSFER_DETAILS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYTYPE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("PROPERTY_TYPE_AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PROPERTY_TYPE_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_TYPE_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROPERTY_TYPE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_PROPERTY_TYPE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROVINCE", b =>
                {
                    b.Property<int>("PROVINCE_CODE")
                        .HasColumnType("int");

                    b.Property<string>("PROVINCE_DESCRITION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSGCCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("REGION_CODE")
                        .HasColumnType("int");

                    b.HasKey("PROVINCE_CODE");

                    b.HasIndex("PROVINCE_CODE")
                        .IsUnique();

                    b.HasIndex("REGION_CODE");

                    b.ToTable("EAMIS_PROVINCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISREGION", b =>
                {
                    b.Property<int>("REGION_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PSGCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("REGION_CODE");

                    b.HasIndex("REGION_CODE")
                        .IsUnique();

                    b.ToTable("EAMIS_REGION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISREQUIREDATTACHMENTS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ATTACHMENT_TYPE_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_REQUIRED")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_REQUIRED_ATTACHMENTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISROLES", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("ROLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_ROLES");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSIGNIFICANTENVIRONMENTALASPECTS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASPECT_DESCPRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EAMIS_ENVIRONMENTALASPECTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUBCLASSIFICATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CLASSIFICATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("NAME_SUBCLASSIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CLASSIFICATION_ID");

                    b.ToTable("EAMIS_SUB_CLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUPPLIER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACCOUNT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ACCOUNT_NUMBER")
                        .HasColumnType("int");

                    b.Property<string>("BANK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRANCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BRGY_CODE")
                        .HasColumnType("int");

                    b.Property<int>("CITY_MUNICIPALITY_CODE")
                        .HasColumnType("int");

                    b.Property<string>("COMPANY_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPANY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_PERSON_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_PERSON_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<int>("PROVINCE_CODE")
                        .HasColumnType("int");

                    b.Property<int>("REGION_CODE")
                        .HasColumnType("int");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BRGY_CODE");

                    b.ToTable("EAMIS_SUPPLIER");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUNITOFMEASURE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SHORT_DESCRIPTION")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UOM_DESCRIPTION")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SHORT_DESCRIPTION")
                        .IsUnique()
                        .HasFilter("[SHORT_DESCRIPTION] IS NOT NULL");

                    b.HasIndex("UOM_DESCRIPTION")
                        .IsUnique()
                        .HasFilter("[UOM_DESCRIPTION] IS NOT NULL");

                    b.ToTable("EAMIS_UNITOFMEASURE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERLOGIN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPUTER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_LOGOUT")
                        .HasColumnType("bit");

                    b.Property<string>("LOGED_IN_TIMESTAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGED_OUT_TIMESTAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("USER_ID");

                    b.ToTable("EAMIS_USER_LOGIN");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERROLES", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<int>("ROLE_ID")
                        .HasColumnType("int");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ROLE_ID");

                    b.HasIndex("USER_ID");

                    b.ToTable("EAMIS_USER_ROLES");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERS", b =>
                {
                    b.Property<int>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AGENCY_EMPLOYEE_NUMBER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_BLOCKED")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PASSWORD_HASH")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PASSWORD_SALT")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_INFO_ID")
                        .HasColumnType("int");

                    b.HasKey("USER_ID");

                    b.HasIndex("AGENCY_EMPLOYEE_NUMBER")
                        .IsUnique()
                        .HasFilter("[AGENCY_EMPLOYEE_NUMBER] IS NOT NULL");

                    b.ToTable("EAMIS_USERS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISWAREHOUSE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BARANGAY_CODE")
                        .HasColumnType("int");

                    b.Property<int>("MUNICIPALITY_CODE")
                        .HasColumnType("int");

                    b.Property<int>("PROVINCE_CODE")
                        .HasColumnType("int");

                    b.Property<int>("REGION_CODE")
                        .HasColumnType("int");

                    b.Property<string>("STREET_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAREHOUSE_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BARANGAY_CODE");

                    b.ToTable("EAMIS_WAREHOUSE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISBARANGAY", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISMUNICIPALITY", null)
                        .WithMany("BARANGAY")
                        .HasForeignKey("BARANGAY_CODE");

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISMUNICIPALITY", "MUNICIPALITY")
                        .WithMany()
                        .HasForeignKey("MUNICIPALITY_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISPROVINCE", "PROVINCE")
                        .WithMany()
                        .HasForeignKey("PROVINCE_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISREGION", "REGION")
                        .WithMany()
                        .HasForeignKey("REGION_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MUNICIPALITY");

                    b.Navigation("PROVINCE");

                    b.Navigation("REGION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISCHARTOFACCOUNTS", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISCLASSIFICATION", "CLASSIFICATION")
                        .WithMany("CHARTOFACCOUNTS")
                        .HasForeignKey("CLASSIFICATIONID");

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISGENERALCHARTOFACCOUNTS", null)
                        .WithMany("EAMIS_CHART_OF_ACCOUNTS")
                        .HasForeignKey("EAMISGENERALCHARTOFACCOUNTSID");

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISGROUPCLASSIFICATION", "GROUPCLASSIFICATION")
                        .WithMany("CHARTOFACCOUNTS")
                        .HasForeignKey("GROUP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISSUBCLASSIFICATION", "SUBCLASSIFICATION")
                        .WithMany("CHARTOFACCOUNTS")
                        .HasForeignKey("SUBCLASSIFICATIONID");

                    b.Navigation("CLASSIFICATION");

                    b.Navigation("GROUPCLASSIFICATION");

                    b.Navigation("SUBCLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISFUNDSOURCE", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISAUTHORIZATION", "AUTHORIZATION")
                        .WithMany("FUND_SOURCE")
                        .HasForeignKey("AUTHORIZATION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISFINANCINGSOURCE", "FINANCING_SOURCE")
                        .WithMany("FUND_SOURCE")
                        .HasForeignKey("FINANCING_SOURCE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISGENERALFUNDSOURCE", "GENERALFUNDSOURCE")
                        .WithMany("FUNDSOURCE")
                        .HasForeignKey("GENERAL_FUND_SOURCE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AUTHORIZATION");

                    b.Navigation("FINANCING_SOURCE");

                    b.Navigation("GENERALFUNDSOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGROUPCLASSIFICATION", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISCLASSIFICATION", "CLASSIFICATION")
                        .WithMany("GROUPCLASSIFICATION")
                        .HasForeignKey("CLASSIFICATION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISSUBCLASSIFICATION", "SUBCLASSIFICATION")
                        .WithMany("GROUPCLASSIFICATION")
                        .HasForeignKey("SUB_CLASSIFICATION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLASSIFICATION");

                    b.Navigation("SUBCLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISITEMCATEGORY", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISCHARTOFACCOUNTS", "CHART_OF_ACCOUNTS")
                        .WithMany("ITEM_CATEGORY")
                        .HasForeignKey("CHART_OF_ACCOUNT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHART_OF_ACCOUNTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISITEMSUBCATEGORY", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISITEMCATEGORY", "ITEM_CATEGORY")
                        .WithMany("ITEM_SUB_CATEGORY")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISPROPERTYITEMS", "PROPERTY_ITEM")
                        .WithMany()
                        .HasForeignKey("PROPERTY_ITEMID");

                    b.Navigation("ITEM_CATEGORY");

                    b.Navigation("PROPERTY_ITEM");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISMUNICIPALITY", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISPROVINCE", "PROVINCE")
                        .WithMany()
                        .HasForeignKey("PROVINCE_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISREGION", "REGION")
                        .WithMany()
                        .HasForeignKey("REGION_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PROVINCE");

                    b.Navigation("REGION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPERSONNELINFO", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISUSERS", "USERS")
                        .WithMany()
                        .HasForeignKey("USERSUSER_ID");

                    b.Navigation("USERS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROPERTYITEMS", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISITEMCATEGORY", "ITEM_CATEGORY")
                        .WithMany("PROPERTY_ITEMS")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISSUPPLIER", "SUPPLIER_GROUP")
                        .WithMany("PROPERTY_ITEMS")
                        .HasForeignKey("SUPPLIER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISUNITOFMEASURE", "UOM_GROUP")
                        .WithMany("PROPERTY_ITEM")
                        .HasForeignKey("UOM_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISWAREHOUSE", "WAREHOUSE_GROUP")
                        .WithMany("PROPERTY_ITEMS")
                        .HasForeignKey("WAREHOUSE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ITEM_CATEGORY");

                    b.Navigation("SUPPLIER_GROUP");

                    b.Navigation("UOM_GROUP");

                    b.Navigation("WAREHOUSE_GROUP");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISPROVINCE", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISREGION", null)
                        .WithMany("PROVINCE")
                        .HasForeignKey("PROVINCE_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISREGION", "REGION")
                        .WithMany()
                        .HasForeignKey("REGION_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("REGION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUBCLASSIFICATION", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISCLASSIFICATION", "CLASSIFICATION")
                        .WithMany("SUBCLASSIFICIATION")
                        .HasForeignKey("CLASSIFICATION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUPPLIER", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISBARANGAY", "BARANGAY_GROUP")
                        .WithMany()
                        .HasForeignKey("BRGY_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BARANGAY_GROUP");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERLOGIN", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISUSERS", "EAMIS_USERS")
                        .WithMany("EAMISUSER_LOGIN")
                        .HasForeignKey("USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EAMIS_USERS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERROLES", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISROLES", "ROLES")
                        .WithMany("USERROLES")
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISUSERS", "USERS")
                        .WithMany("USER_ROLES")
                        .HasForeignKey("USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ROLES");

                    b.Navigation("USERS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISWAREHOUSE", b =>
                {
                    b.HasOne("EAMIS.Core.Domain.Entities.EAMISBARANGAY", "BARANGAY")
                        .WithMany()
                        .HasForeignKey("BARANGAY_CODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BARANGAY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISAUTHORIZATION", b =>
                {
                    b.Navigation("FUND_SOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISCHARTOFACCOUNTS", b =>
                {
                    b.Navigation("ITEM_CATEGORY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISCLASSIFICATION", b =>
                {
                    b.Navigation("CHARTOFACCOUNTS");

                    b.Navigation("GROUPCLASSIFICATION");

                    b.Navigation("SUBCLASSIFICIATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISFINANCINGSOURCE", b =>
                {
                    b.Navigation("FUND_SOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGENERALCHARTOFACCOUNTS", b =>
                {
                    b.Navigation("EAMIS_CHART_OF_ACCOUNTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGENERALFUNDSOURCE", b =>
                {
                    b.Navigation("FUNDSOURCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISGROUPCLASSIFICATION", b =>
                {
                    b.Navigation("CHARTOFACCOUNTS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISITEMCATEGORY", b =>
                {
                    b.Navigation("ITEM_SUB_CATEGORY");

                    b.Navigation("PROPERTY_ITEMS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISMUNICIPALITY", b =>
                {
                    b.Navigation("BARANGAY");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISREGION", b =>
                {
                    b.Navigation("PROVINCE");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISROLES", b =>
                {
                    b.Navigation("USERROLES");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUBCLASSIFICATION", b =>
                {
                    b.Navigation("CHARTOFACCOUNTS");

                    b.Navigation("GROUPCLASSIFICATION");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISSUPPLIER", b =>
                {
                    b.Navigation("PROPERTY_ITEMS");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUNITOFMEASURE", b =>
                {
                    b.Navigation("PROPERTY_ITEM");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISUSERS", b =>
                {
                    b.Navigation("EAMISUSER_LOGIN");

                    b.Navigation("USER_ROLES");
                });

            modelBuilder.Entity("EAMIS.Core.Domain.Entities.EAMISWAREHOUSE", b =>
                {
                    b.Navigation("PROPERTY_ITEMS");
                });
#pragma warning restore 612, 618
        }
    }
}
